name: OTA Arduino Compiler
version: 1.0.0
slug: ota_arduino_compiler
description: "Compile and upload Arduino code via TFTP in Home Assistant"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
ports:
  69/udp: 69
init: false
services: []
options: {}
schema:
  sketch_file: str
  target_ip: str
  board_type: str